In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv ('https://raw.githubusercontent.com/CunyLaguardiaDataAnalytics/datasets/master/mtcars.csv')

In [8]:
#how many rows and columns in this data set?
df.shape

(32, 12)

In [9]:
#what are the column names?
df.columns

Index(['Unnamed: 0', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs',
       'am', 'gear', 'carb'],
      dtype='object')

In [10]:
#preview the data set
df.head(5)

,Unnamed: 0,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [11]:
df.describe()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.0000
mean,20.090625,6.187500,230.721875,146.687500,3.596563,3.217250,17.848750,0.437500,0.406250,3.687500,2.8125
std,6.026948,1.785922,123.938694,68.562868,0.534679,0.978457,1.786943,0.504016,0.498991,0.737804,1.6152
min,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.0000
25%,15.425000,4.000000,120.825000,96.500000,3.080000,2.581250,16.892500,0.000000,0.000000,3.000000,2.0000
50%,19.200000,6.000000,196.300000,123.000000,3.695000,3.325000,17.710000,0.000000,0.000000,4.000000,2.0000
75%,22.800000,8.000000,326.000000,180.000000,3.920000,3.610000,18.900000,1.000000,1.000000,4.000000,4.0000
max,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,8.0000

In [12]:
#rename column with missing name
df = df.rename(columns = {'Unnamed: 0': 'Car Make/Model'})
df.head()

,Car Make/Model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [13]:
#create a new dataframe subsetting the original columns

df2=df[['Car Make/Model','mpg','hp', 'wt', 'cyl']]
df2.head()

      Car Make/Model   mpg   hp     wt  cyl
0          Mazda RX4  21.0  110  2.620    6
1      Mazda RX4 Wag  21.0  110  2.875    6
2         Datsun 710  22.8   93  2.320    4
3     Hornet 4 Drive  21.4  110  3.215    6
4  Hornet Sportabout  18.7  175  3.440    8

In [14]:
#rename the above columns to show full name

df3 = df2.rename(columns={'mpg':'Miles Per Gallon', 'hp': 'Horse Power', 'wt': 'Weight', 'cyl': 'Cylinder'})
df3.head()

      Car Make/Model  Miles Per Gallon  Horse Power  Weight  Cylinder
0          Mazda RX4              21.0          110   2.620         6
1      Mazda RX4 Wag              21.0          110   2.875         6
2         Datsun 710              22.8           93   2.320         4
3     Hornet 4 Drive              21.4          110   3.215         6
4  Hornet Sportabout              18.7          175   3.440         8

In [15]:
df3.describe ()

       Miles Per Gallon  Horse Power     Weight   Cylinder
count         32.000000    32.000000  32.000000  32.000000
mean          20.090625   146.687500   3.217250   6.187500
std            6.026948    68.562868   0.978457   1.785922
min           10.400000    52.000000   1.513000   4.000000
25%           15.425000    96.500000   2.581250   4.000000
50%           19.200000   123.000000   3.325000   6.000000
75%           22.800000   180.000000   3.610000   8.000000
max           33.900000   335.000000   5.424000   8.000000

In [16]:
#what are all of the different vehicle types?

df3['Car Make/Model']

0               Mazda RX4
1           Mazda RX4 Wag
2              Datsun 710
3          Hornet 4 Drive
4       Hornet Sportabout
5                 Valiant
6              Duster 360
7               Merc 240D
8                Merc 230
9                Merc 280
10              Merc 280C
11             Merc 450SE
12             Merc 450SL
13            Merc 450SLC
14     Cadillac Fleetwood
15    Lincoln Continental
16      Chrysler Imperial
17               Fiat 128
18            Honda Civic
19         Toyota Corolla
20          Toyota Corona
21       Dodge Challenger
22            AMC Javelin
23             Camaro Z28
24       Pontiac Firebird
25              Fiat X1-9
26          Porsche 914-2
27           Lotus Europa
28         Ford Pantera L
29           Ferrari Dino
30          Maserati Bora
31             Volvo 142E
Name: Car Make/Model, dtype: object

In [20]:
# filter data and find summary stats for only one type of vehicle, first pick one make:
df3.iloc[[19,20]]

    Car Make/Model  Miles Per Gallon  Horse Power  Weight  Cylinder
19  Toyota Corolla              33.9           65   1.835         4
20   Toyota Corona              21.5           97   2.465         4

In [21]:
#then calculate summary stats for these two vehicles
df3.iloc[[19,20]].describe()

       Miles Per Gallon  Horse Power    Weight  Cylinder
count          2.000000     2.000000  2.000000       2.0
mean          27.700000    81.000000  2.150000       4.0
std            8.768124    22.627417  0.445477       0.0
min           21.500000    65.000000  1.835000       4.0
25%           24.600000    73.000000  1.992500       4.0
50%           27.700000    81.000000  2.150000       4.0
75%           30.800000    89.000000  2.307500       4.0
max           33.900000    97.000000  2.465000       4.0